version: "3"

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    image: ym4shida/rocker:tidyverse.4.2.1
    container_name: rstudio
    ports:
      - 8787:8787
    volumes:
      - ./data/:/home/rstudio/
    environment:
      - DISABLE_AUTH=true
